-- =============================================
-- EssLearn Database Schema - Initial Setup
-- Migration ID: 001_initial_schema.sql
-- Created: 2026-04-28
-- =============================================

-- Enable necessary extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================
-- 1. LearningFields Table
-- =============================================
CREATE TABLE IF NOT EXISTS "LearningFields" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL UNIQUE,
    "Description" text,
    "Icon" text,
    "Color" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY ("Id")
);

-- =============================================
-- 2. Channels Table
-- =============================================
CREATE TABLE IF NOT EXISTS "Channels" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "YoutubeChannelId" character varying(100) NOT NULL UNIQUE,
    "Title" character varying(300) NOT NULL,
    "Description" text,
    "ThumbnailUrl" text,
    "SubscriberCount" bigint NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY ("Id")
);

-- =============================================
-- 3. Playlists Table
-- =============================================
CREATE TABLE IF NOT EXISTS "Playlists" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "FieldId" integer NOT NULL,
    "ChannelId" integer,
    "YoutubePlaylistId" character varying(100),
    "Title" character varying(500) NOT NULL,
    "Description" text,
    "ThumbnailUrl" text,
    "SourceUrl" text,
    "PublishedAt" timestamp with time zone,
    "TotalVideos" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Playlists_LearningFields_FieldId" FOREIGN KEY ("FieldId") REFERENCES "LearningFields" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Playlists_Channels_ChannelId" FOREIGN KEY ("ChannelId") REFERENCES "Channels" ("Id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Playlists_YoutubePlaylistId" 
ON "Playlists" ("YoutubePlaylistId") 
WHERE "YoutubePlaylistId" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "IX_Playlists_FieldId" ON "Playlists" ("FieldId");
CREATE INDEX IF NOT EXISTS "IX_Playlists_ChannelId" ON "Playlists" ("ChannelId");

-- =============================================
-- 4. Videos Table
-- =============================================
CREATE TABLE IF NOT EXISTS "Videos" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "PlaylistId" integer NOT NULL,
    "YoutubeVideoId" character varying(20),
    "DownloadedVideoId" character varying(20),
    "Title" character varying(500) NOT NULL,
    "Description" text,
    "ThumbnailUrl" text,
    "Url" text,
    "DurationSeconds" integer NOT NULL DEFAULT 0,
    "Position" integer NOT NULL,
    "PublishedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Videos_Playlists_PlaylistId" FOREIGN KEY ("PlaylistId") REFERENCES "Playlists" ("Id") ON DELETE CASCADE
    CONSTRAINT "FK_Videos_DownloadedVideos_DownloadVideoId" FOREIGN KEY ("DownloadedVideoId") REFERENCES "DownloadedVideos" ("Id") ON DELETE CASCADE

);

CREATE INDEX IF NOT EXISTS "IX_Videos_PlaylistId_Position" ON "Videos" ("PlaylistId", "Position");

-- =============================================
-- 5. VideoProgress Table
-- =============================================
CREATE TABLE IF NOT EXISTS "VideoProgresses" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "VideoId" integer NOT NULL UNIQUE,
    "Status" integer NOT NULL DEFAULT 0,
    "WatchedSeconds" integer NOT NULL DEFAULT 0,
    "LastWatchedAt" timestamp with time zone,
    "CompletedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY ("Id"),
    CONSTRAINT "FK_VideoProgresses_Videos_VideoId" FOREIGN KEY ("VideoId") REFERENCES "Videos" ("Id") ON DELETE CASCADE
);

-- =============================================
-- 6. DownloadedVideos Table
-- =============================================
CREATE TABLE IF NOT EXISTS "DownloadedVideos" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "VideoId" integer NOT NULL UNIQUE,
    "VideoId1" integer UNIQUE,
    "FormatId" character varying(50) NOT NULL,
    "Container" character varying(20) NOT NULL,
    "Quality" character varying(50) NOT NULL,
    "VideoCodec" text,
    "AudioCodec" text,
    "Width" integer,
    "Height" integer,
    "FileSizeBytes" bigint NOT NULL DEFAULT 0,
    "FilePath" character varying(1000) NOT NULL,
    "DownloadedAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DownloadedVideos_Videos_VideoId" FOREIGN KEY ("VideoId") REFERENCES "Videos" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DownloadedVideos_Videos_VideoId1" FOREIGN KEY ("VideoId1") REFERENCES "Videos" ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_DownloadedVideos_VideoId" ON "DownloadedVideos" ("VideoId");
CREATE INDEX IF NOT EXISTS "IX_DownloadedVideos_VideoId1" ON "DownloadedVideos" ("VideoId1");

-- =============================================
-- 7. Roadmaps Table
-- =============================================
CREATE TABLE IF NOT EXISTS "Roadmaps" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(500) NOT NULL,
    "Description" text,
    "Iconurl" text,
    "Progress" double precision NOT NULL DEFAULT 0.0,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY ("Id")
);

-- =============================================
-- 8. RoadmapNodes Table
-- =============================================
CREATE TABLE IF NOT EXISTS "RoadmapNodes" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "RoadmapId" integer NOT NULL,
    "PlaylistId" integer NOT NULL,
    "ParentId" integer,
    "Position" integer NOT NULL,
    "LevelOrder" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoadmapNodes_Roadmaps_RoadmapId" FOREIGN KEY ("RoadmapId") REFERENCES "Roadmaps" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RoadmapNodes_Playlists_PlaylistId" FOREIGN KEY ("PlaylistId") REFERENCES "Playlists" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RoadmapNodes_RoadmapNodes_ParentId" FOREIGN KEY ("ParentId") REFERENCES "RoadmapNodes" ("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "IX_RoadmapNodes_RoadmapId" ON "RoadmapNodes" ("RoadmapId");
CREATE INDEX IF NOT EXISTS "IX_RoadmapNodes_PlaylistId" ON "RoadmapNodes" ("PlaylistId");
CREATE INDEX IF NOT EXISTS "IX_RoadmapNodes_ParentId" ON "RoadmapNodes" ("ParentId");

-- =============================================
-- 9. BlobStorageLogs Table
-- =============================================
CREATE TABLE IF NOT EXISTS "BlobStorageLogs" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Operation" character varying(50) NOT NULL,
    "BlobBucket" character varying(255) NOT NULL,
    "BlobPath" character varying(1000) NOT NULL,
    "Success" boolean NOT NULL,
    "ErrorMessage" text,
    "Metadata" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_BlobStorageLogs_CreatedAt" ON "BlobStorageLogs" ("CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_BlobStorageLogs_BlobPath" ON "BlobStorageLogs" ("BlobPath");

-- =============================================
-- 10. StorageIntegrity Table
-- =============================================
CREATE TABLE IF NOT EXISTS "StorageIntegrity" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "BlobBucket" character varying(255) NOT NULL,
    "BlobPath" character varying(1000) NOT NULL,
    "Sha256Hash" character varying(64) NOT NULL,
    "ExpectedSize" bigint NOT NULL,
    "ActualSize" bigint NOT NULL,
    "IsValid" boolean NOT NULL DEFAULT true,
    "ErrorMessage" text,
    "CheckedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_StorageIntegrity_BlobPath" ON "StorageIntegrity" ("BlobPath");
CREATE INDEX IF NOT EXISTS "IX_StorageIntegrity_CheckedAt" ON "StorageIntegrity" ("CheckedAt");

-- =============================================
-- Completion
-- =============================================
-- Database schema initialized successfully!
