-- Drop old mismatched roadmap tables
DROP TABLE IF EXISTS "RoadmapNodePrerequisites" CASCADE;
DROP TABLE IF EXISTS "RoadmapNodes" CASCADE;
DROP TABLE IF EXISTS "Roadmaps" CASCADE;

-- Create Roadmaps with correct schema matching EF entity
CREATE TABLE "Roadmaps" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(500) NOT NULL,
    "Description" character varying(1000),
    "Category" character varying(100) NOT NULL DEFAULT 'Custom',
    "Color" character varying(20) NOT NULL DEFAULT '#3b82f6',
    "Icon" character varying(500),
    "Tags" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY ("Id")
);

-- Create RoadmapNodes with correct schema matching EF entity
CREATE TABLE "RoadmapNodes" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "RoadmapId" integer NOT NULL,
    "Title" character varying(300) NOT NULL,
    "Description" character varying(500),
    "Status" integer NOT NULL DEFAULT 0,
    "Duration" character varying(20),
    "MediaType" integer NOT NULL DEFAULT 0,
    "ResourceCount" integer NOT NULL DEFAULT 1,
    "PositionX" integer NOT NULL DEFAULT 0,
    "PositionY" integer NOT NULL DEFAULT 0,
    "materialId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoadmapNodes_Roadmaps_RoadmapId" FOREIGN KEY ("RoadmapId") REFERENCES "Roadmaps" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_RoadmapNodes_RoadmapId" ON "RoadmapNodes" ("RoadmapId");

-- Create RoadmapNodePrerequisites join table
CREATE TABLE "RoadmapNodePrerequisites" (
    "NodeId" integer NOT NULL,
    "PrerequisiteId" integer NOT NULL,
    PRIMARY KEY ("NodeId", "PrerequisiteId"),
    CONSTRAINT "FK_RoadmapNodePrerequisites_RoadmapNodes_NodeId" FOREIGN KEY ("NodeId") REFERENCES "RoadmapNodes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RoadmapNodePrerequisites_RoadmapNodes_PrerequisiteId" FOREIGN KEY ("PrerequisiteId") REFERENCES "RoadmapNodes" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_RoadmapNodePrerequisites_PrerequisiteId" ON "RoadmapNodePrerequisites" ("PrerequisiteId");
