-- Create Roadmap table
CREATE TABLE "Roadmaps" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(500) NOT NULL,
    "Description" text,
    "Iconurl" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "Progress" double precision NOT NULL DEFAULT 0.0,
    PRIMARY KEY ("Id")
);

-- Create RoadmapNode table
CREATE TABLE "RoadmapNodes" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "RoadmapId" integer NOT NULL,
    "PlaylistId" integer NOT NULL,
    "ParentId" integer,
    "Position" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "LevelOrder" integer NOT NULL,
    PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoadmapNodes_Roadmaps_RoadmapId" FOREIGN KEY ("RoadmapId") REFERENCES "Roadmaps" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RoadmapNodes_Playlists_PlaylistId" FOREIGN KEY ("PlaylistId") REFERENCES "Playlists" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RoadmapNodes_RoadmapNodes_ParentId" FOREIGN KEY ("ParentId") REFERENCES "RoadmapNodes" ("Id") ON DELETE SET NULL
);

-- Create indexes for RoadmapNodes
CREATE INDEX "IX_RoadmapNodes_RoadmapId" ON "RoadmapNodes" ("RoadmapId");
CREATE INDEX "IX_RoadmapNodes_PlaylistId" ON "RoadmapNodes" ("PlaylistId");
CREATE INDEX "IX_RoadmapNodes_ParentId" ON "RoadmapNodes" ("ParentId");
